import "@/assets/css/globals.css";
import "antd/dist/reset.css"; // Import CSS Antd (Ant Design 5+)
import { AntdRegistry } from "@ant-design/nextjs-registry"; // Hỗ trợ CSS-in-JS

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
    shortcut: "/favicon-32x32.png",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
